### PR TITLE
Feat/a colour coding

### PR DESCRIPTION
**Pull request by ssumaiyaahmed**
## Type of Change
- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation update
- [ ] Other (please describe):

## Description
Brief description of the changes this pull request includes.
- Added colour coding
- fixed frontend and backend bug
- added bug reason txt

## Self Code Review
- [ ] I have reviewed my own code changes thoroughly
- [ ] I have run any relevant tests locally 
- [ ] I have ensured that my changes are well-documented and any necessary comments are added
- [ ] I have provided meaningful variable names, function names, and comments to aid in code readability and understanding
- [ ] I have handled error cases and edge cases appropriately

### CODE REVIEW

**Review by JamieHvizdos — APPROVED** [review]
Looks good!

**Review by shannon-ab — APPROVED** [review]

**Review by martinl498 — APPROVED** [review]

**Review by chrisnathan20 — APPROVED** [review]
Great Bugfix!

**Review by fransbudiman — APPROVED** [review]

**Review by shannon-ab — APPROVED** [review]

**Review by JamieHvizdos — APPROVED** [review]
Looks good!

**Review by ashvini8 — APPROVED** [review]
looks good!

**Review by shannon-ab — APPROVED** [review]

**Pull request merged**
